name: PR Autolabeler

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - master

jobs:
  auto-label:
    name: Auto Label
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Autolabel PR
        uses: release-drafter/release-drafter/autolabeler@v7
        env:
          GITHUB_TOKEN: ${{ secrets.CICD_TOKEN }}
